<?php require_once 'templates/layout/header.phtml'; ?>


<div class="container mt-5">
    <h2 class="text-center">Editar Categorias</h2>
    <form action="editarcategorias/<?= htmlspecialchars($categoria->ID_categoria) ?>" method="POST">

        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" name="nombre" id="nombre" required>
        </div>

       
        <button type="submit" class="btn btn-primary btn-block">Enviar</button>
    </form>
</div>

<?php require_once 'templates/layout/footer.phtml'; ?>