<?php require_once 'templates/layout/header.phtml' ?>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"><?= htmlspecialchars($prenda->nombre) ?></h1>
                    <p class="card-text"><?= htmlspecialchars($prenda->descripcion) ?></p>
                    <p class="card-text">$ <?= htmlspecialchars($prenda->valor) ?></p>
                    <p class="card-text">Categoría: <?= htmlspecialchars($prenda->categoria_nombre) ?></p>

                    <?php if (!empty($prenda->Imagen)): ?>
                        <img src="<?= htmlspecialchars($prenda->Imagen) ?>" class="imagenproducto img-fluid" alt="Imagen de la categoría">
                    <?php else: ?>
                        <p>No se encontró la imagen.</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once 'templates/layout/footer.phtml' ?>
